name: train_model_v1
version: 33
display_name: Train Model

type: command

inputs:
  input_data:
    type: uri_folder

outputs:
  output_path:
    type: uri_folder

environment: azureml:mle-env@latest

code: .
command: >
  python train_component.py --input_data ${{inputs.input_data}} --output_path ${{outputs.output_path}}
