name: mle-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - openpyxl
  - xlrd
  - matplotlib
  - seaborn
  - pip
  - pip:
      - joblib
      - shap
      - xgboost
      - mlflow
      - azureml-mlflow 
      - azure-ai-ml==1.17.0
      - azure-identity
      - marshmallow==3.20.1 
      - tqdm
      - azureml-inference-server-http
  